### ISSUE TITLE
Use GraalVM to provide more language support + es6 support

### ISSUE THREAD

**Issue by StephenOTT** [zeebe-io/zeebe-script-worker#2]
GraalVm has a larger selection of scripts languages that are supported, and their GraalJS supports es6 , so there is better node package support.

Also, specifically for JS, Graal is several times faster in execution of JS, compared to nashorn.

**Comment by saig0** [comment]
Hi @StephenOTT, thank you for the proposal. I'll have a look into it.

Are you only interested in the better JS engine, or do you want to use other languages?

**Comment by saig0** [comment]
I tried to integrate GraalVM. It works in the tests but I'm not able to embed it into Spring Boot.

**Comment by StephenOTT** [comment]
@saig0 what is the issue you are hitting with graalvm?  I was using spring boot with the js context of graal in a previous prototype i did.

**Comment by saig0** [comment]
I embed the GraalVM into Spring Boot (https://github.com/zeebe-io/zeebe-script-worker/blob/graalvm/pom.xml#L79-L89).

When I run the Spring Boot JAR and open a context then I get a `FileSystemNotFoundException` (https://github.com/zeebe-io/zeebe-script-worker/blob/graalvm/src/main/java/io/zeebe/script/GraalEvaluator.java#L38).

**Comment by StephenOTT** [comment]
@saig0  remove the dep

```
<dependency>
			<groupId>org.graalvm.js</groupId>
			<artifactId>js</artifactId>
			<version>${version.graalvm}</version>
</dependency>
```

as Js is included in GraalVM.

Then with SDK man ensure to have the VM installed with like `sdk install java 1.0.0-rc9-graal`

If you are using IDE (like intelliJ) make sure to update your project SDK to map to the graal vm installed.

**Comment by StephenOTT** [comment]
@saig0 also you might want to consider using Vertx instead of spring boot.  Vertx has a pretty seamless integration with Graal and non-graal es6 support: https://github.com/reactiverse/es4x.

Would be really interesting to connect zeebe to the vertx eventbus so that vertx workers can pick up jobs.  This is extra interesting because of the auto-scalling features of Vertx and the automatic polyglot support. I think this fits really well with the zeebe scale

**Comment by StephenOTT** [comment]
You could just make the graal supoort optional. Allowing someone to use the graalVM if they chose to, and this if they did they would be able to execute multiple languages supported within their Runtime installation. Could do something like a env var to indicate to use the graalVM context.  Or detect it.

**Comment by saig0** [comment]
Ok, I can make the support optional.

**Comment by saig0** [comment]
Let's leave it as it is for now.
