### ISSUE TITLE
Add support for Kotlin Scripting (JSR223)

### ISSUE THREAD

**Issue by aivinog1** [zeebe-io/zeebe-script-worker#72]
I'm thinking about adding support for the Kotlin script. Kotlin Scripting Engine supports JSR223, see an example there: https://github.com/JetBrains/kotlin/tree/master/libraries/examples/kotlin-jsr223-local-example

**Comment by saig0** [comment]
I like the idea :+1:

**Comment by aivinog1** [comment]
I will add a PR with this in an hour :)
